### ISSUE TITLE
Add to PYPI

### ISSUE THREAD

**Issue by mikkeloscar** [kyrias/python-srcinfo#1]
Hello,

Would it be possible to add this package to [pypi](https://pypi.python.org/pypi)? I know it's in the community repo, but it would be convenient if it could be fetched from pypi as well.

**Comment by kyrias** [comment]
Essentially the only reason I haven't done it yet is that I've not really worked on it for half a year, but if you think it'd be useful I certainly will upload it.

**Comment by mikkeloscar** [comment]
That would be great! Thanks for the quick response!

**Comment by kyrias** [comment]
[Done](https://pypi.python.org/pypi/srcinfo). Will add a note about it to the README in a bit.

**Comment by mikkeloscar** [comment]
I appreciate it!

**Comment by kyrias** [comment]
No problem; just let me know if there's anything you're wondering, or anything that you think should be changed, and feel free to contribute if you can/want to.
