### ISSUE TITLE
Script should return valid JSON

### ISSUE THREAD

**Issue by djmattyg007** [kyrias/python-srcinfo#2]
This lets you usefully make use of the output of the parse_srcinfo script with programs that parse JSON to easily extract individual pieces of data in scripts and bash one-liners.

**Comment by kyrias** [comment]
Feel free to add it as an optional thing when given a `--json` argument, but I'm not planning on adding it myself since it was only add it to quickly test the parsing.

**Comment by djmattyg007** [comment]
Is there any chance you could tag a new release with my changes?

**Comment by kyrias** [comment]
Done.
